import { createClient } from "@supabase/supabase-js";

function isMissingTableError(message: string | null | undefined): boolean {
  if (!message) return false;
  return message.includes('relation "healthcheck" does not exist');
}

export default async function SupabaseCheckPage() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !anonKey) {
    return (
      <main style={{ padding: 24 }}>
        <h1>Supabase Check</h1>
        <p>Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY.</p>
      </main>
    );
  }

  const supabase = createClient(supabaseUrl, anonKey);
  const { data, error } = await supabase
    .from("healthcheck")
    .select("*")
    .limit(1);

  const hasData = Array.isArray(data) && data.length > 0;
  const showMissingTableHelp = isMissingTableError(error?.message);

  return (
    <main style={{ padding: 24 }}>
      <h1>Supabase Check</h1>
      {hasData && !error ? (
        <>
          <p>Supabase OK</p>
          <pre>{JSON.stringify(data[0], null, 2)}</pre>
        </>
      ) : (
        <>
          <p>Supabase ERROR</p>
          <p>{error?.message ?? "No rows found in healthcheck table."}</p>
        </>
      )}

      {showMissingTableHelp ? (
        <section>
          <h2>Create the table</h2>
          <p>In Supabase SQL editor, run:</p>
          <pre>
{`create table if not exists public.healthcheck (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now()
);

insert into public.healthcheck default values;`}
          </pre>
        </section>
      ) : null}
    </main>
  );
}
